// Average effective property tax rates by state (2024 data)
// Source: Tax Foundation, U.S. Census Bureau
export const stateTaxRates = [
  { code: '', name: 'Custom / Manual', rate: null },
  { code: 'AL', name: 'Alabama', rate: 0.41 },
  { code: 'AK', name: 'Alaska', rate: 1.04 },
  { code: 'AZ', name: 'Arizona', rate: 0.62 },
  { code: 'AR', name: 'Arkansas', rate: 0.62 },
  { code: 'CA', name: 'California', rate: 0.71 },
  { code: 'CO', name: 'Colorado', rate: 0.51 },
  { code: 'CT', name: 'Connecticut', rate: 2.15 },
  { code: 'DE', name: 'Delaware', rate: 0.57 },
  { code: 'FL', name: 'Florida', rate: 0.86 },
  { code: 'GA', name: 'Georgia', rate: 0.92 },
  { code: 'HI', name: 'Hawaii', rate: 0.29 },
  { code: 'ID', name: 'Idaho', rate: 0.63 },
  { code: 'IL', name: 'Illinois', rate: 2.07 },
  { code: 'IN', name: 'Indiana', rate: 0.83 },
  { code: 'IA', name: 'Iowa', rate: 1.57 },
  { code: 'KS', name: 'Kansas', rate: 1.41 },
  { code: 'KY', name: 'Kentucky', rate: 0.86 },
  { code: 'LA', name: 'Louisiana', rate: 0.55 },
  { code: 'ME', name: 'Maine', rate: 1.36 },
  { code: 'MD', name: 'Maryland', rate: 1.07 },
  { code: 'MA', name: 'Massachusetts', rate: 1.20 },
  { code: 'MI', name: 'Michigan', rate: 1.54 },
  { code: 'MN', name: 'Minnesota', rate: 1.12 },
  { code: 'MS', name: 'Mississippi', rate: 0.65 },
  { code: 'MO', name: 'Missouri', rate: 0.97 },
  { code: 'MT', name: 'Montana', rate: 0.74 },
  { code: 'NE', name: 'Nebraska', rate: 1.73 },
  { code: 'NV', name: 'Nevada', rate: 0.55 },
  { code: 'NH', name: 'New Hampshire', rate: 2.18 },
  { code: 'NJ', name: 'New Jersey', rate: 2.47 },
  { code: 'NM', name: 'New Mexico', rate: 0.67 },
  { code: 'NY', name: 'New York', rate: 1.72 },
  { code: 'NC', name: 'North Carolina', rate: 0.82 },
  { code: 'ND', name: 'North Dakota', rate: 0.98 },
  { code: 'OH', name: 'Ohio', rate: 1.56 },
  { code: 'OK', name: 'Oklahoma', rate: 0.87 },
  { code: 'OR', name: 'Oregon', rate: 0.97 },
  { code: 'PA', name: 'Pennsylvania', rate: 1.58 },
  { code: 'RI', name: 'Rhode Island', rate: 1.63 },
  { code: 'SC', name: 'South Carolina', rate: 0.57 },
  { code: 'SD', name: 'South Dakota', rate: 1.22 },
  { code: 'TN', name: 'Tennessee', rate: 0.71 },
  { code: 'TX', name: 'Texas', rate: 1.80 },
  { code: 'UT', name: 'Utah', rate: 0.58 },
  { code: 'VT', name: 'Vermont', rate: 1.90 },
  { code: 'VA', name: 'Virginia', rate: 0.82 },
  { code: 'WA', name: 'Washington', rate: 0.84 },
  { code: 'WV', name: 'West Virginia', rate: 0.58 },
  { code: 'WI', name: 'Wisconsin', rate: 1.85 },
  { code: 'WY', name: 'Wyoming', rate: 0.57 },
  { code: 'DC', name: 'Washington D.C.', rate: 0.56 },
];
